In [91]:
import numpy as np
c=np.zeros((10,1))
k=0.1
r=np.zeros((11,1))
for i in range(0,11):
    r[i]=k*i
t=10**-5

def f(c,tm):
    f=np.zeros((10,1))
    f[0]=-3*c[0]+4*c[1]-c[2]
    for i in range(1,10):
        if i<9:
            f[i]=c[i+1]*(k*i+k)+c[i-1]*(k*i-k)-2*c[i]*(k*i)-(tm**2)*(c[i]**2)*(k**3)*i
        else:
            f[i]=1*(k*i+k)+c[i-1]*(k*i-k)-2*c[i]*(k*i)-(tm**2)*(c[i]**2)*(k**3)*i
    return f

def J(c,tm):
    J=np.zeros((10,10))
    J[0,0]=-3
    J[0,1]=4
    J[0,2]=-1
    for i in range(1,10):
        fd_m1=k*i-k
        fd_m2=-2*k*i-(tm**2)*2*c[i]*(k**3)*i
        fd_m3=k*i+k
        J[i,i-1]=fd_m1
        J[i,i]=fd_m2
        if i<9:
            J[i,i+1]=fd_m3
    return J

def NR(c,tm):
    s=1
    count=0
    while s==1:
        c1=c-np.dot(np.linalg.inv(J(c,tm)),f(c,tm))
        count=count+1
        if (abs(c1-c)<t).all():
            s=0
            #print(count)
            return c1
        else:
            c=c1
NR(c,0.9)
NR(c,2)
NR(c,10)

array([[ 0.1029912 ],
       [ 0.10482249],
       [ 0.11031637],
       [ 0.12026079],
       [ 0.13608   ],
       [ 0.16038574],
       [ 0.19802588],
       [ 0.25852392],
       [ 0.36237773],
       [ 0.55987969]])

In [68]:
NR(c,0.9)

array([[ 0.98111628],
       [ 0.981302  ],
       [ 0.98185913],
       [ 0.98278917],
       [ 0.98409383],
       [ 0.98577594],
       [ 0.98783897],
       [ 0.99028728],
       [ 0.99312605],
       [ 0.99636131]])

In [69]:
NR(c,2)

array([[ 0.91379926],
       [ 0.91459592],
       [ 0.91698588],
       [ 0.92099832],
       [ 0.92666766],
       [ 0.93405181],
       [ 0.94322313],
       [ 0.95427535],
       [ 0.96732376],
       [ 0.98250887]])

In [71]:
NR(c,10)

array([[ 0.32407685],
       [ 0.32661682],
       [ 0.33423671],
       [ 0.34777581],
       [ 0.36839661],
       [ 0.39833514],
       [ 0.44124592],
       [ 0.50352997],
       [ 0.59693849],
       [ 0.74493112]])

In [88]:
if abs((np.array([2,2])-np.array([3,-1]))<2.5).any():
    print(1)

1


In [86]:
abs(np.array([2,2])-np.array([3,-1]))<2.5

array([ True, False], dtype=bool)